blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.blog_create, name='create'),
    path('blog/', views.BlogsListView.as_view(), name='blog'),
    path('blogs/<int:pk>', views.BlogsDetailView.as_view(), name='blogs-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('blogs/<int:pk>/comment', views.BlogCommentCreate.as_view(), name='comment'),
]

task_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
    path('', RedirectView.as_view(url='blogs/')),
    path('accounts/', include('django.contrib.auth.urls')),
]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Used to generate URLs by reversing the URL patterns
from django.urls import reverse


class blogs(models.Model):
    """Model representing a blog"""
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, help_text='Enter a brief description')
    photo = models.ImageField(upload_to='uploads/')
    # slug = models.SlugField('',max_length=60)

    # Foreign Key used because blog can only have one author, but authors can have multiple blogs
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    pub_date = models.DateTimeField('Publish Date', auto_now=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this blog."""
        return reverse('blogs-detail', args=[str(self.id)])


class Author(models.Model):
    """Model representing an author."""
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField('Bio', max_length=700)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id}, {self.name}'

class Comment(models.Model):
    """Model representing a comment on the blog."""
    comment = models.TextField(max_length=300, help_text='Enter a your comment')
    blog = models.ForeignKey('blogs',on_delete=models.SET_NULL, null=True)
    comment_date = models.DateTimeField('Comment Date',auto_now_add=True)
    user = models.ForeignKey(User,on_delete=models.SET_NULL, null=True, blank = True)

    class Meta:
        ordering = ['comment_date']

    def __str__(self):
        """String for representing the Model object."""
        return self.comment

blogs/forms.py
from django.forms import ModelForm

from blogs.models import Comment
from blogs.models import blogs


class CommentModelForm(ModelForm):
    def clean_comment(self):
        data = self.cleaned_data['comment']
        # return the cleaned data.
        return data

    class Meta:
        model = Comment
        fields = ['comment', 'blog']
        labels = {'comment': ('Comment')}
        help_texts = {'comment': ('Enter your comment here')}


# Defining modelForm for "createBlogform"
class blogsCreateForm(ModelForm):
    class Meta:
        model = blogs
        exclude = ["author", "pub_date"]

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.http import JsonResponse
from django.template.loader import render_to_string


from blogs.models import blogs, Author, Comment
from django.views import generic


from blogs.forms import CommentModelForm
from blogs.forms import blogsCreateForm


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_blogs = blogs.objects.all().count()
    num_authors = Author.objects.all().count()
    num_comments = Comment.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_blogs,
        'num_authors': num_authors,
        'num_comments': num_comments,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


def blog_create(request):
    data = dict()

    if request.method == 'POST':
        form = blogsCreateForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = blogsCreateForm()

    context = {'form': form}

    data['html_form'] = render_to_string('blogs/includes/partial_blog_create.html',
        context,
        request=request,
    )
    return JsonResponse(data)
    
# class BlogsCreateView(generic.CreateView):
#     model = blogs
#     form_class = blogsCreateForm

#     # Overriding default get method
#     def get(self, *args, **kwargs):
#         form = self.form_class()
#         return render(self.request, self.template_name, {"createForm": form})

#     # Overriding default post method of the generic view
#     def post(self, *args, **kwargs):
#         if self.request.method == "POST" and self.request.is_ajax():
#             form = self.form_class(self.request.POST)
#             form.save()
#             return JsonResponse({"success": True}, status=200)
#         return JsonResponse({"success": False}, status=400)


class BlogsListView(generic.ListView):
    model = blogs  # model that we are using the class for
    paginate_by = 5
    context_object_name = 'blogs_list'  # template variable name
    queryset = blogs.objects.all()
    template_name = 'blogs/blogs_name_list.html'


class BlogsDetailView(generic.DetailView):
    model = blogs


class AuthorListView(generic.ListView):
    model = Author  # model that we are using the class for
    context_object_name = 'author_list'  # template variable name
    queryset = Author.objects.all()
    template_name = 'blogs/Author_name_list.html'


class AuthorDetailView(generic.DetailView):
    model = Author


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Form for adding a blog comment. Requires login. 
    """
    model = Comment
    fields = ['comment', ]

    def get_context_data(self, **kwargs):
        """
        Add associated blog to form template so can display its title in HTML.
        """
        # Call the base implementation first to get a context
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Get the blog from id and add it to the context
        context['blogs'] = get_object_or_404(blogs, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add user and associated blog to form data before setting it as valid (so it is saved to model)
        """
        # Add logged-in user as user of comment
        form.instance.user = self.request.user
        # Associate comment with blog based on passed id
        form.instance.blog = get_object_or_404(blogs, pk=self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        After posting comment return to associated blog.
        """
        return reverse('blogs-detail', kwargs={'pk': self.kwargs['pk'], })

blogs/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Add jQuery static file -->
  {% block title %}<title>Blogs</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <script type="text/javascript" src="{{ STATIC_URL }} /static/jquery-3.5.1.js">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  {% block extra_js%}
  <script src="http://malsup.github.com/jquery.form.js"></script>
  {% endblock %}
  
<!-- custom js file -->

  <script src="{% static 'blogs/js/blogs.js' %}"></script>
  
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'blog' %}">All Blogs</a></li>
          <li><a href="{% url 'authors' %}">All Authors</a></li>
          <button type="button" class="btn btn-primary js-create-blog">Create Blog</button>
          {% if user.is_authenticated %}
          <li>User: {{ user.get_username }}</li>
          <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %}
        </ul>
        {% endblock %}
      </div>

      <div class="col-sm-10 ">
        {% block content %}{% endblock %}

        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
        {% endblock %}
      </div>
      <div class="modal fade" id="modal-blog">
        <div class="modal-dialog">
          <div class="modal-content">
          </div>
        </div>
      </div>
    </div>
</html>

blogs/templates/blogs/Author_name_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Authors to show.</p>
  {% endif %}       
{% endblock %}

blogs/templates/blogs/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ author.name }}</h1>
<br />
<h3>Title: {{ author.date_of_birth }}</h3>
<br />
<div style="margin-left:20px;margin-top:20px">
    <p>{{ author.bio }}</p>
</div>
<hr>
<h3>Blogs by {{ author.name }}</h3>
<br />
{% for blog in author.blogs_set.all %}
<h6>
    <a href="{% url 'blogs-detail' blog.pk %}">{{ blog.title }}</a> on {{ blog.pub_date }}
</h6>
{% endfor %}
{% endblock %}

blogs/templates/blogs/blogs_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ blogs.title }}</h1>
<h3>Publish Date: {{ blogs.pub_date }}</h3>

<div style="margin-left:20px;margin-top:20px">

    <img src="{{blogs.photo.url}}" />
    <p>{{ blogs.description }}</p>
</div>
<br />
<br />
<div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

    {% for copy in blogs.comment_set.all %}
    <hr>
    <h4>
        {{ copy.user }} says :
    </h4>
    <p>
        {{ copy.comment }}
    <p>
        {{ copy.comment_date }}
    </p>
    </p>

    {% endfor %}
    {% if user.is_authenticated %}
        <a href="{% url 'comment' blogs.id %}">Add Comment</a>
    {% else %}
        <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
    {% endif %}
</div>
<br />
<br />
<p><strong>Author:</strong> <a href="{% url 'author-detail' blogs.author.pk %}">{{ blogs.author }}</a></p>
<!-- author detail link not yet defined -->
{% endblock %}

blogs/templates/blogs/blogs_name_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogs List</h1>
  {% if blogs_list %}
  <ul>
    {% for blog in blogs_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{ blog.author }},{{blog.pub_date}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Blogs to show.</p>
  {% endif %}       
{% endblock %}

blogs/templates/blogs/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blogs-detail' blogs.pk %}">{{blogs.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

blogs/templates/blogs/includes/partial_blog_create.html
{% load widget_tweaks %}

<!-- defining the action attr to let django know where to submit the form -->
<form method="post" action="{% url 'create' %}" class = js-blog-create-form>
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new Blog</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Blog</button>
  </div>
</form>

blogs/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Blogs Home</h1>
<p>Welcome to Blogs</p>
<h2>Dynamic content</h2>
<p>The blogs has the following record counts:</p>
<ul>
  <li><strong>Blogs:</strong> {{ num_books }}</li>
  <li><strong>Authors:</strong> {{ num_authors }}</li>
  <li><strong>Comments:</strong> {{ num_comments }}</li>
</ul>

<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}